# Generated by configure script
CC = gcc
CFLAGS = -Wall -Wextra -std=c99 -O2 -g
LDFLAGS = 
LIBS = -lm -lSDL2  -lGL  -lpthread
SDL2_CFLAGS = -I/usr/include/SDL2 -D_REENTRANT 
SDL2_LIBS = -lSDL2 
OPENGL_LIBS = -lGL 
PTHREAD_LIBS = -lpthread

# Features
HAVE_SDL2 = 1
HAVE_OPENGL = 1
HAVE_PTHREAD = 1

# Platform
PLATFORM = Linux
ARCH = x86_64

# Version
VERSION = 0.1.0
